spring.application.name=chatbot
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/linkdin_ensam
spring.data.mongodb.database=linkdin_ensam
ollama.base-url=http://localhost:11434
ollama.model=llama3.1:8b
server.tomcat.connection-timeout=300000
spring.mvc.async.request-timeout=300000
